# erhe configuration file

[imgui]
window_viewport = true
padding         = 2.0
rounding        = 3.0

[window]
show             = true
fullscreen       = false
use_transparency = false
# Ddefaul is 4.6
#gl_major         = 4
#gl_minor         = 5 # llvm pipe requires 4.5 - but needs also ERHE_SERIAL_INIT defined - see top of editor.cpp

#size             = [ 3072, 1728 ]
size              = [ 2560, 1440 ]
#size             = [ 2432, 1376 ]
#size             = [ 1920, 1080 ]
#size             = [ 1792, 1024 ]
#size             = [ 32, 256 ]
use_finish       = false
use_sleep        = false
sleep_margin     = 0.0 # 0.002 would be 2ms - TODO measure; This is ignored (and value 0.0 is used) with OpenXR
swap_interval    = 0   # try 0; This is ignored (and value 0 is used) with OpenXR
enable_joystick  = false

# Buffer sizes use megabytes as unit
[mesh_memory]
vertex_buffer_size = 1280
index_buffer_size  =  512

# NOTE: Primitive is as GLTF primitive (NOT triangle etc)
[renderer]
max_material_count  = 1000
max_light_count     = 20
max_camera_count    = 256
max_joint_count     = 1000
#max_primitive_count = 50000
#max_draw_count      = 50000
max_primitive_count = 6000
max_draw_count      = 6000

[physics]
static_enable  = true
dynamic_enable = true

[scene]
imgui_window_scene_view      = true # NOTE This is ignored with OpenXR at the moment
camera_exposure              =   1.0
shadow_range                 =  30.0
directional_light_intensity  =   4.0 # formation total intensity
directional_light_radius     =   4.5 # formation radius
directional_light_height     =  10.0 # formation height
directional_light_count      =  5
spot_light_intensity         = 500.0
spot_light_radius            =  10.0 # formation radius
spot_light_height            =   5.0 # formation height
spot_light_count             =   0
floor_size                   = 32.0
mass_scale                   = 8.0
floor                        = true
detail                       = 4
camera_distance              = 4.0
camera_elevation             = 1.3 # Sitting person eye height
instance_count               = 1
instance_gap                 = 0.50
object_scale                 = 0.25
make_johnson_solid_brushes   = true
make_platonic_solid_brushes_ = true
make_curved_brushes          = true
# Value of 0.25 object scale makes edges of platonic solids to be 25cm.
# That makes height of all platonic solids to be around 40cm at most.

[hud]
# When left commented, defaults to false on Desktop, true on OpenXR
#enabled = true
show    = false
locked  = false
width   =  3072
height  =  2048
ppm     =  3400
x       =  0.00
y       =  0.00
z       = -0.03

[hotbar]
enabled    = true
show       = true
use_radial = false
# Uncomment to override defaults which are set in Hotbar::Hotbar()
# Desktop defaults
#x          =  0.0   # 64
#y          = -0.140 # 64
#z          = -0.5   # 64
# OpenXR defaults
#x         = -0.02
#y         =  0.09
#z         = -0.28

[viewport]
polygon_fill              = true
# edge_lines                = true TODO need separate values for desktop vs OpenXr
edge_lines                = true
selection_polygon_fill    = true
selection_edge_lines      = true
corner_points             = false
polygon_centroids         = false
selection_bounding_box    = false # Both false -> show smallest volume
selection_bounding_sphere = false #
edge_color                = [ 0.0, 0.0, 0.0, 0.5 ] # Note - use premultiplied linear values
selection_edge_color      = [ 0.0, 0.0, 0.0, 0.5 ] #
clear_color               = [ 0.05, 0.05, 0.05 ]
gizmo_scale               = 10.0


[transform_tool]
show_translate = true
show_rotate    = false

[grid]
snap_enabled = true
# visible      = true
visible      = false # TODO this needs separate value for Desktop vs OpenXR
major_color  = [ 0.0, 0.0, 0.0 ]
minor_color  = [ 0.0, 0.0, 0.0 ]
major_width  = 4.0
minor_width  = 0.75
cell_size    = 1.0
cell_div     = 2
cell_count   = 100

[camera_controls]
invert_x           = false
invert_y           = false
sensitivity        = 1.0
velocity_damp      = 0.92
velocity_max_delta = 0.004
move_power         = 1000.0
move_speed         = 2.0
turn_speed         = 1.0

#  D e v e l o p e r   S e c t i o n  #
#                                     #
#       ..                            #
#      .::':::. .::::.   .:''.  .     #
#    .::'   '::::::' .:::'    ''      #
#     `     ..:'    ..:'              #
#                                     #
#    H e r e   b e   d r a g o n s    #
[developer]
enable = false

[network]
upstream_address   = "127.0.0.1"
upstream_port      = 34567
downstream_address = "0.0.0.0"
downstream_port    = 34567

[graphics]
initial_clear                = true
post_processing              = true # Note: This is ignored (and set to false) for OpenXR
#force_bindless_textures_off  = true
#force_no_persistent_buffers  = true
#force_no_direct_state_access = true
#force_no_multi_draw_indirect = true
#force_gl_version             = 450
#force_glsl_version           = 450

[threading]
thread_count = 8

[renderdoc]
capture_support = false

# Mixing ID renderer based picking and ray trace based picking
# has the issue that ID renderer has latency of a frame or few.
# With some camera motion, this causes picking to "see" meshes
# (picked using ID renderer) in front of the grid (picked using
# ray intersection test), even if the mesh is some distance behind
# the grid
[id_renderer]
enabled = false

[text_renderer]
enabled   = true
font_size = 14 # TODO This needs separate value when using Desktop vs OpenXR

[shader_monitor]
enabled = true

# OpenXR has been tested with Oculus Quest. In the distant past, also with Oculus Rift S and Varjo XR3 were tested.
[headset]
#	openxr          = true
#openxr_mirror   = true
#quad_view       = true
#debug           = true
#depth           = true
#visibility_mask = true
#hand_tracking   = true
#passthrough_fb  = true # Useful with mirror mode, for example
