['high graphics preset']
msaa_sample_count = 8
name = 'high graphics preset'
shadow_enable = true
shadow_light_count = 8
shadow_resolution = 4096

['low graphics preset']
msaa_sample_count = 2
name = 'low graphics preset'
shadow_enable = true
shadow_light_count = 6
shadow_resolution = 3072