[graphics]
preset = 'Low Graphics Preset'

[icons]
hotbar_icon_size = 80
large_icon_size = 32
small_icon_size = 24

[imgui]
font_size = 24.0
icon_font_size = 24.0
material_design_font_size = 24.0
mono_font = 'res/fonts/SourceCodePro-Semibold.otf'
primary_font = 'res/fonts/SourceSansPro-Regular.otf'
vr_font_size = 22.0