#
# erhe configuration file for hextiles
#

[imgui]
window_viewport = false

[window]
show             = true
fullscreen       = false
use_transparency = false
gl_major         = 4
gl_minor         = 6
width            = 512
height           = 512
use_finish       = false
use_sleep        = false
swap_interval    = 1 # try 0

[graphics]
initial_clear               = true
force_no_bindless           = false
force_no_persistent_buffers = false

#  D e v e l o p e r   S e c t i o n  
#                                     
#       ..                            
#      .::':::. .::::.   .:''.  .     
#    .::'   '::::::' .:::'    ''      
#     `     ..:'    ..:'              
#                                     
#    H e r e   b e   d r a g o n s    

# Buffer sizes use megabytes as unit
[mesh_memory]
vertex_buffer_size = 20
index_buffer_size  =  8

[threading]
parallel_init = false

[renderdoc]
capture_support = true

[text_renderer]
enabled   = true
font_size = 14

[shader_monitor]
enabled = true
